package constants

// 日志模板集中管理：任何业务字段变更都必须同步修改对应模板与调用处。
const (
	LogUserRegisterStart       = "user register start"
	LogUserRegisterSuccess     = "user register success"
	LogUserLoginSuccess        = "user login success"
	LogUserLoginFailed         = "user login failed"
	LogUserProfileUpdate       = "user profile update"
	LogClientCreateSuccess     = "client create success"
	LogClientUpdateSuccess     = "client update success"
	LogClientDeleteSuccess     = "client delete success"
	LogCaseCreateSuccess       = "case create success"
	LogCaseCreateFailed        = "case create failed"
	LogCaseUpdateSuccess       = "case update success"
	LogCaseStatusChangeSuccess = "case status change success"
	LogCaseStatusChangeFailed  = "case status change failed"
	LogCaseAssignSuccess       = "case assign success"
	LogCaseAssignFailed        = "case assign failed"
	LogDocumentUploadSuccess   = "document upload success"
	LogDocumentUploadFailed    = "document upload failed"
	LogDocumentDeleteSuccess   = "document delete success"
	LogBillingCreateSuccess    = "billing create success"
	LogBillingCreateFailed     = "billing create failed"
	LogBillingPaidSuccess      = "billing paid success"
	LogBillingPaidFailed       = "billing paid failed"
	LogBillingInvoicedSuccess  = "billing invoiced success"
	LogBillingVoidSuccess      = "billing void success"
	LogBillingSummary          = "billing summary"
	LogAuditWriteFailed        = "audit log write failed"
	LogUploadFileSuccess       = "upload file success"
	LogUploadFileFailed        = "upload file failed"
	LogRateLimitHit            = "rate limit hit"
	LogCommentCreateFailed     = "unused comment template"

	// 利益冲突检查日志模板
	LogConflictSubmitHit       = "conflict check submit hit"
	LogConflictSubmitNoHit     = "conflict check submit no hit"
	LogConflictSubmitFailed    = "conflict check submit failed"
	LogConflictIdempotentReuse = "conflict check duplicate submit collapsed to unique record"
	LogConflictReleaseSuccess  = "conflict check release success"
	LogConflictReleaseFailed   = "conflict check release failed"
	LogConflictRejectSuccess   = "conflict check reject success"
	LogConflictRejectFailed    = "conflict check reject failed"
	LogConflictInvalidated     = "conflict check released decision invalidated because profile changed"
	LogConflictRevalidateStale = "conflict check read revalidated stale decision"
	LogPartyUpsertSuccess      = "case party upsert success"
	LogPartyUpdateSuccess      = "case party update success"
	LogPartyVersionBump        = "case party version bumped, invalidating bound decisions"
)
